[package]
name = "http_server"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.177"
serde = "1.0.228"
serde_json = "1.0.145"
syscalls = "0.7.0"
tokio = { version = "1.49.0", features = ["macros", "rt"] }

[dev-dependencies]
tokio = { version = "1.49.0", features = ["macros", "rt", "time"] }
